### ISSUE TITLE
Add chunmi.cooker.k1pro1 support

### ISSUE THREAD

**Issue by marrobHD** [syssi/xiaomi_cooker#38]
Error:
```
Logger: homeassistant.setup
Source: custom_components/xiaomi_miio_cooker/__init__.py:149
Integration: xiaomi_miio_cooker (documentation, issues)
First occurred: 16:13:49 (1 occurrences)
Last logged: 16:13:49

Error during setup of component xiaomi_miio_cooker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miio_cooker/__init__.py", line 160, in setup
    update(utcnow())
  File "/config/custom_components/xiaomi_miio_cooker/__init__.py", line 149, in update
    if state.mode in [OperationMode.Running, OperationMode.AutoKeepWarm]:
  File "/usr/local/lib/python3.8/site-packages/miio/cooker.py", line 481, in mode
    return OperationMode(self.data["func"])
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: None is not a valid OperationMode
```

**Comment by tieppm** [comment]
your model is i YLIH02CM IH 1S 3L chunmi.cooker.k1pro1 ?

**Comment by marrobHD** [comment]
Yes

**Comment by tieppm** [comment]
Yes. Me too

**Comment by tieppm** [comment]
@syssi please fit it, thank U

**Comment by syssi** [comment]
Duplicate #46

**Comment by syssi** [comment]
Duplicate #11.
