### ISSUE TITLE
ERROR (MainThread) [supervisor.store] https://github.com/syssi/xiaomi_cooker is not a valid add-on repository

### ISSUE THREAD

**Issue by mkania11** [syssi/xiaomi_cooker#43]
Usiluje zainstalować komponent w Home Assistant OS 6.3 i mam komunikat jak wyżej.
W jaki sposób to obejsc/rozwiązać?

Marcin Kania

**Comment by mkania11** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/xiaomi_miio_cooker/__init__.py:166
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:52:08 (15 occurrences)
Last logged: 23:12:33

[548200674304] {'code': -9999, 'message': 'user ack timeout'}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 185, in async_turn_on
    await self._on_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1531, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_miio_cooker/__init__.py", line 166, in start_service
    cooker.start(profile)
  File "/usr/local/lib/python3.9/site-packages/miio/cooker.py", line 647, in start
    self.send("set_start", [profile])
  File "/usr/local/lib/python3.9/site-packages/miio/device.py", line 97, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.9/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise DeviceError(error)
miio.exceptions.DeviceError: {'code': -9999, 'message': 'user ack timeout'}

**Comment by syssi** [comment]
It looks like the initial issue was solved. This custom component is an integration which can be installed via HACS. This isn't an add-on.
