### ISSUE TITLE
Any update on how to integrate this chunmi.cooker.normalcd1

### ISSUE THREAD

**Issue by forci0ne** [syssi/xiaomi_cooker#45]
2021-11-07 19:14:53 ERROR (MainThread) [homeassistant.setup] Error during setup of component xiaomi_miio_cooker
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
result = await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/xiaomi_miio_cooker/__init__.py", line 160, in setup
update(utcnow())
File "/config/custom_components/xiaomi_miio_cooker/__init__.py", line 149, in update
if state.mode in [OperationMode.Running, OperationMode.AutoKeepWarm]:
File "/usr/local/lib/python3.9/site-packages/miio/cooker.py", line 481, in mode
return OperationMode(self.data["func"])
File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
raise ve_exc
ValueError: 1 is not a valid OperationMode
2021-11-07 19:14:53 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform xiaomi_miio_cooker.sensor: Unable to set up component.

**Comment by forci0ne** [comment]
2021-11-07 19:20:52 INFO (SyncWorker_6) [custom_components.xiaomi_miio_cooker] Initializing with host 192.168.1.109 (token 97fd8...)
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [miio.miioprotocol] Got a response: Container:
data = Container:
data = b'' (total 0)
value = b'' (total 0)
offset1 = 32
offset2 = 32
length = 0
header = Container:
data = b'!1\x00 \x00\x00\x00\x00\x12Q\x16\x15\x00\x00\x07\xf7' (total 16)
value = Container:
length = 32
unknown = 0
device_id = unhexlify('12511615')
ts = 1970-01-01 00:33:59
offset1 = 0
offset2 = 16
length = 16
checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [miio.miioprotocol] Discovered 12511615 with ts: 1970-01-01 00:33:59, token: b'ffffffffffffffffffffffffffffffff'
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [miio.miioprotocol] 192.168.1.109:54321 >>: {'id': 1, 'method': 'get_prop', 'params': ['all']}
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [miio.miioprotocol] 192.168.1.109:54321 (ts: 1970-01-01 00:34:00, id: 1) << {'id': 1, 'result': [1, '0000000001', 0, 60, '00000e1061881903', '0000000061881903', '1100', 1, 1, 35, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, '0009570a', '00000007', 0], 'exe_time': 10}
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [miio.cooker] Count (12) of requested properties does not match the count (24) of received values.
2021-11-07 19:20:52 DEBUG (SyncWorker_6) [custom_components.xiaomi_miio_cooker] Got new state: <CookerStatus cooking_delayed=61881903 custom=TypeError duration=1100 favorite=TypeError firmware_version=TypeError hardware_version=TypeError interaction_timeouts=TypeError menu=1 mode=ValueError remaining=ValueError settings=TypeError stage=TypeError start_time=TypeError temperature=TypeError>

**Comment by RalXYZ** [comment]
@syssi Any progress on this issue? Is there any debug information missing?
I also own this device, and I am looking forward to supporting it.  
I would like to provide any debug information if necessary. 🙂
